// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Assets struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	UrlPath   string `json:"urlPath"`
	FileID    int64  `json:"fileID"`
	CreatorID int64  `json:"creatorID"`
}

type Files struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Mimetype string `json:"mimetype"`
	Data     []byte `json:"data"`
}
